# Generated by Django 2.1.7 on 2019-02-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190228_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_role',
            field=models.CharField(choices=[('superuser', 'Supeuser'), ('channel_admin', 'Channel Admin'), ('client', 'Client')], default='client', max_length=30),
        ),
    ]
