# Generated by Django 2.1.7 on 2019-04-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='status',
            field=models.CharField(default='Unsold', max_length=256),
        ),
    ]
